#!/usr/bin/env bash

#dub wait localhost 9300 20


function check_availability(){
	count=0
	step=1
	
	while [[ -z $(printf "GET / HTTP/1.0\r\n\r\n" | nc $1 $2 | grep -e '200 OK') ]]; do
    		sleep $step;
    		count=$(expr $count + $step)
    		if [ $count -gt $3 ]; then
        		return 0
    		fi
	done
	return 1;
}

## Check cmd
if [ $# -lt 1 ]
then
        echo "Usage : $0 <CMD> <args>"
        exit
fi

CMD=$1

case "$CMD" in
	wait) 	echo "waiting"
		if [ $# != 4 ]
		then
			echo "Usage : $0 wait <HOST> <PORT> <TIMEOUT>"
			exit; 
		fi
		HOST=$2
		PORT=$3
		TIMEOUT=$4
		;;
	*) echo "dat aint no cmd.."
	   exit;;
esac
echo "$HOST, $PORT, $TIMEOUT"

#shift
#while getopts ":a:p:drh" opt; do
#  case "$opt" in
#    a) echo $OPTARG;;
#  esac
#done


## Check availability
#start_timeout_exceeded=false
#count=0
#step=10

#while [[ -z $(printf "GET / HTTP/1.0\r\n\r\n" | nc localhost 8083 | grep -e '200 OK') ]]; do
#    sleep $step;
#    count=$(expr $count + $step)
#    if [ $count -gt $START_TIMEOUT ]; then
#        start_timeout_exceeded=true
#        break
#    fi
#done

if check_availability $HOST $PORT $TIMEOUT; then
    echo "Not able to auto-create topic (waited for $TIMEOUT sec)"
    exit 1
fi